name: Test deploy to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      actions: read
      contents: read

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Set K8s context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - uses: azure/setup-kubectl@v4
        id: install
        with:
          version: 'v1.29.9'

      - name: Deploys application
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: kubernetes
          namespace: nginx
